"""
quiz_questions_data.py
=================================================================
Static, curated question bank for every quiz in QUIZ_CATALOG
(frontend/views.py). This is Option C from the earlier discussion:

  1. Drafted once (here) — real questions on the actual topic of each
     quiz, not the old placeholder Python/SQL quiz that used to show
     for every single quiz regardless of subject.
  2. >>> NEEDS A HUMAN REVIEW PASS BEFORE PRODUCTION / GRADED USE <<<
     Skim each quiz_id's questions for accuracy before relying on this
     for scored student attempts. Nothing here was reviewed by anyone
     but the model that drafted it.
  3. Once reviewed, it's loaded into the QuizQuestion table by a data
     migration (frontend/migrations/0008_quiz_questions.py) and served
     from the database from then on — no live API calls, no per-use
     cost, no risk of a bad question appearing during a live demo.

Format: { quiz_id: [ (question_text, [4 choices], correct_index, explanation), ... ] }
quiz_id values must match the 'id' field of QUIZ_CATALOG entries.
"""

QUIZ_QUESTIONS = {

    "perf-basics": [
        ("What does LCP (Largest Contentful Paint) measure?",
         ["Time to first byte", "Render time of the largest visible content element", "Total page size", "Number of HTTP requests"],
         1, "LCP measures how long the largest visible element (image or text block) takes to render — a key signal of perceived load speed."),
        ("Which of these is one of Google's current Core Web Vitals?",
         ["TTFB", "INP", "DOM depth", "Page weight"],
         1, "The current Core Web Vitals are LCP, INP, and CLS. TTFB is a related but separate metric."),
        ("What does CLS stand for?",
         ["Content Layout Speed", "Cumulative Layout Shift", "Cascading Load Sequence", "Critical Loading State"],
         1, "CLS measures how much visible content unexpectedly shifts position during page load."),
        ("A fast Time to First Byte (TTFB) means:",
         ["The browser finished rendering", "The server responded quickly to the initial request", "All images have loaded", "JavaScript finished executing"],
         1, "TTFB is purely about server response speed to the first request — it happens before any rendering."),
        ("Which technique commonly reduces image-related load time without a visible quality loss?",
         ["Increasing image resolution", "Compression / modern formats like WebP or AVIF", "Removing all images", "Loading images before HTML"],
         1, "Modern compressed formats keep visual quality high while significantly cutting file size."),
        ("What is 'render-blocking' content?",
         ["A JavaScript runtime error", "Resources like CSS/JS that must load before the browser can display page content", "A CDN outage", "A broken image link"],
         1, "Render-blocking resources delay the browser from painting anything until they've finished loading."),
    ],

    "testing-concepts": [
        ("What is a 'test case'?",
         ["A bug report", "A documented set of steps, inputs, and expected results used to verify a specific behavior", "An automation script only", "A production incident log"],
         1, "A test case is a structured, repeatable definition of what to test and what result to expect."),
        ("What is boundary value analysis used for?",
         ["Testing at and around the edges of valid input ranges, where defects are more likely", "Testing UI color schemes", "Load testing only", "Testing server uptime"],
         0, "Defects often cluster at the boundaries of valid input ranges (e.g. min/max), so testing right at those edges is high-value."),
        ("Which best describes black-box testing?",
         ["Testing based on internal code structure", "Testing behavior against requirements, without knowledge of the internal code", "Reading source code line by line", "Testing internal functions directly"],
         1, "Black-box testing evaluates what the system does, from the outside, without needing to know how it's implemented internally."),
        ("What is regression testing?",
         ["Testing only brand-new features", "Re-running tests to confirm existing functionality still works after a change", "Testing performance under heavy load", "Testing only the visual design"],
         1, "Regression testing protects against a new change accidentally breaking something that used to work."),
        ("What distinguishes a smoke test from a full regression suite?",
         ["Smoke tests are exhaustive; regression tests are quick", "Smoke tests are a small, fast set of checks confirming basic functionality before deeper testing", "They're the same thing", "Smoke tests only run in production"],
         1, "A smoke test is a quick sanity check run before investing time in a longer, deeper test pass."),
        ("Which test type focuses on how independent modules work together?",
         ["Unit testing", "Integration testing", "Acceptance testing", "Smoke testing"],
         1, "Integration testing specifically checks the interactions between separately-developed components/modules."),
    ],

    "seo-keyword-basics": [
        ("What is 'search intent'?",
         ["The keyword's character length", "The underlying goal behind a user's search (informational, navigational, transactional, etc.)", "The number of ads on a results page", "A specific ranking algorithm's name"],
         1, "Search intent describes *why* someone is searching — what they actually want to accomplish."),
        ("A 'long-tail keyword' is best described as:",
         ["A single, very popular one-word search term", "A longer, more specific phrase with typically lower volume but higher intent match", "A keyword banned by search engines", "A keyword used only in image alt text"],
         1, "Long-tail keywords are more specific phrases — lower search volume individually, but often higher conversion/relevance."),
        ("What is 'keyword stuffing'?",
         ["Using a keyword excessively/unnaturally in an attempt to manipulate rankings", "A recommended, legitimate SEO strategy", "Adding a keyword to alt text once", "Translating a keyword into other languages"],
         0, "Keyword stuffing is an outdated, manipulative practice that modern search engines penalize rather than reward."),
        ("Which best signals topical relevance to a search engine?",
         ["Scattering random unrelated keywords throughout the page", "Well-organized content that naturally covers a topic in depth using related terms", "Repeating one exact phrase dozens of times", "Hiding text using the background color"],
         1, "Genuine topical depth and naturally related terminology signal real relevance far better than repetition or keyword tricks."),
        ("What is the primary goal of on-page SEO content?",
         ["Ranking for as many unrelated keywords as possible", "Satisfying both search-engine relevance signals and genuine user needs", "Maximizing word count regardless of quality", "Avoiding the use of headings"],
         1, "Good on-page SEO aligns what search engines reward with what actually helps the reader."),
        ("Which of these is a recognized search-intent category?",
         ["Transactional", "Vertical", "Horizontal", "Cached"],
         0, "The common intent categories are informational, navigational, transactional, and commercial-investigation."),
    ],

    "responsive-web-design": [
        ("What is the purpose of a CSS media query?",
         ["To load external fonts", "To apply different styles based on device characteristics like screen width", "To compress images", "To validate HTML syntax"],
         1, "Media queries let CSS adapt styling conditionally, most commonly based on viewport width."),
        ("What does 'mobile-first' design mean?",
         ["Designing only for mobile devices", "Designing base styles for small screens first, then progressively enhancing for larger ones", "Designing exclusively in landscape mode", "Ignoring desktop users entirely"],
         1, "Mobile-first means the smallest-screen styles are the default, with larger-screen styles layered on top via media queries."),
        ("Which unit is commonly used for flexible, viewport-relative sizing?",
         ["px only", "vw / vh (viewport width/height)", "pt (points)", "in (inches)"],
         1, "vw/vh scale relative to the viewport, making them useful for fluid, responsive sizing."),
        ("What does `width=device-width` in the viewport meta tag do?",
         ["Sets a fixed 980px layout", "Matches the CSS viewport width to the device's actual screen width", "Disables zooming entirely", "Forces landscape orientation"],
         1, "It tells the browser to use the device's real width as the layout viewport width, instead of a default desktop-sized fallback."),
        ("In a responsive layout, 'flexible' elements typically:",
         ["Resize/reflow based on available space rather than fixed pixel dimensions", "Are hidden on every screen except desktop", "Load in a random order", "Ignore their parent container entirely"],
         0, "Flexible/fluid elements adapt to the space available instead of being locked to fixed dimensions."),
        ("Responsive breakpoints are typically chosen to:",
         ["Target only one screen size", "Adjust layout around common device width ranges (mobile, tablet, desktop)", "Change font colors only", "Apply only to print stylesheets"],
         1, "Breakpoints mark the widths at which the layout needs to change to stay usable across device sizes."),
    ],

    "seo-fundamentals": [
        ("What is the primary purpose of a meta description?",
         ["It's a direct Google ranking factor", "It's a summary shown in search results that can influence click-through rate", "It sets the page's canonical URL", "It defines the page's character encoding"],
         1, "Meta descriptions aren't a direct ranking factor, but a compelling one can meaningfully improve click-through rate."),
        ("What is a canonical tag used for?",
         ["Blocking a page from being indexed", "Telling search engines which URL is the preferred version among duplicate/similar pages", "Automatically redirecting users", "Setting the page's title"],
         1, "Canonical tags resolve ambiguity when the same or similar content is reachable via multiple URLs."),
        ("Which heading structure is generally best practice?",
         ["Multiple H1 tags scattered with no hierarchy", "A single descriptive H1, followed by a logical H2/H3 hierarchy", "Only H6 tags throughout", "No headings, only bold text"],
         1, "A clear, single-H1 hierarchy helps both users and search engines understand the page's structure."),
        ("What does 'indexing' mean in an SEO context?",
         ["A search engine storing and organizing a page's content so it can appear in results", "Translating a page into other languages", "Compressing a page's file size", "Assigning a page a paid ranking slot"],
         0, "Indexing is the process by which a search engine adds a crawled page to its searchable database."),
        ("A `noindex` meta tag tells search engines to:",
         ["Crawl the page more frequently", "Exclude the page from search results", "Prioritize the page's ranking", "Redirect the page to HTTPS"],
         1, "`noindex` explicitly asks search engines not to include that page in their search results."),
        ("What's the difference between the title tag and the H1 in SEO best practice?",
         ["They must always be identical text", "The title tag drives the browser tab/search result title, while H1 is the main on-page heading — related but can differ", "H1 controls indexing, the title tag does not", "Title tags are deprecated"],
         1, "They serve related but distinct purposes and don't have to be word-for-word identical."),
    ],

    "automation-tools": [
        ("What's the main benefit of running tests in a CI/CD pipeline?",
         ["It eliminates the need for any manual testing", "Tests run automatically on each code change, catching regressions early and consistently", "It guarantees zero production bugs", "It only benefits front-end code"],
         1, "Automated CI/CD testing catches issues quickly and consistently, though it doesn't eliminate the value of manual/exploratory testing."),
        ("What is the main purpose of a test automation framework?",
         ["To eliminate the need for test cases", "To provide reusable structure/tooling for writing, organizing, and running automated tests consistently", "To manually execute tests faster by hand", "To replace version control"],
         1, "A framework standardizes how automated tests are written and run, making the suite maintainable at scale."),
        ("What is a 'flaky test'?",
         ["A test that always fails", "A test that passes or fails inconsistently without any code changes, undermining trust in the suite", "A test written in a scripting language", "A test that only runs on Fridays"],
         1, "Flaky tests are unreliable — they intermittently fail for reasons unrelated to the actual code under test."),
        ("What does 'test coverage' typically measure?",
         ["The number of testers on a team", "The proportion of code (or requirements) exercised by the test suite", "The speed of test execution", "The number of production incidents"],
         1, "Coverage quantifies how much of the codebase is actually exercised by existing tests."),
        ("Why run smoke tests before a full automated regression suite?",
         ["To skip testing entirely", "To quickly verify basic functionality works before investing time in the longer full suite", "Smoke tests replace the regression suite entirely", "Smoke tests only test performance"],
         1, "Smoke tests act as a fast gate — no point running a long suite against a fundamentally broken build."),
        ("What's a key risk of over-relying on end-to-end UI automation instead of unit tests?",
         ["UI tests are always faster and more stable than unit tests", "UI/E2E tests tend to be slower and more brittle, so over-relying on them can make the suite fragile and slow", "UI tests can't be automated at all", "There's no meaningful difference"],
         1, "E2E tests are valuable but generally slower and more prone to breaking from unrelated UI changes than focused unit tests."),
    ],

    "core-web-vitals-deep-dive": [
        ("INP (Interaction to Next Paint) primarily measures:",
         ["How quickly a page loads its first byte", "The responsiveness of a page to user interactions throughout its lifecycle", "The total number of images on a page", "The page's total file size"],
         1, "INP tracks how quickly the page responds visually to user interactions across the whole session, not just the first one."),
        ("A 'good' LCP score, per Google's published thresholds, is generally:",
         ["Under 2.5 seconds", "Under 10 seconds", "Exactly 5 seconds", "Over 4 seconds"],
         0, "Google's guidance places 'good' LCP at 2.5 seconds or less, measured at the 75th percentile of page loads."),
        ("What commonly causes poor CLS?",
         ["Fast server response times", "Images, ads, or embeds loading without reserved space, causing content to shift", "Using semantic HTML", "Minifying CSS"],
         1, "Elements that load without a reserved size push surrounding content around as they appear, causing layout shift."),
        ("INP replaced which earlier Core Web Vital metric in 2024?",
         ["LCP", "FID (First Input Delay)", "TTFB", "CLS"],
         1, "INP became the official interactivity metric in March 2024, replacing FID, which only measured the *first* interaction."),
        ("Which is a practical fix for image-caused layout shift?",
         ["Removing all images from the page", "Explicitly setting width/height (or aspect-ratio) on image elements", "Loading every image synchronously before any text", "Increasing image file size"],
         1, "Reserving space via explicit dimensions lets the browser lay out the page correctly before the image finishes loading."),
        ("Core Web Vitals are primarily intended to measure:",
         ["Server-side database performance only", "Real-world, user-centric page experience — loading, interactivity, and visual stability", "Search engine crawl frequency", "Domain registration age"],
         1, "They're designed around what a real user actually experiences while using the page, not internal backend metrics."),
    ],

    "usability-reliability": [
        ("In NFR terms, 'usability' refers to:",
         ["How fast the server processes requests", "How easily and effectively users can learn and use a system to achieve their goals", "The system's uptime percentage", "The number of features in an app"],
         1, "Usability is about the human experience of operating the system effectively, not backend performance."),
        ("'Reliability' as a non-functional requirement is best described as:",
         ["How visually appealing the interface is", "The system's ability to perform its required functions consistently, without failure, over time", "The number of test cases written", "How quickly new features ship"],
         1, "Reliability is about consistent, failure-free operation over time under expected conditions."),
        ("Which of these is an example of error-tolerance design?",
         ["Showing a raw stack trace to end users", "Validating input and giving a clear, actionable error message instead of crashing", "Silently ignoring all errors", "Permanently disabling a feature after one error"],
         1, "Good error tolerance means failures are handled gracefully and communicated clearly, not hidden or catastrophic."),
        ("Mean Time Between Failures (MTBF) is commonly used to assess:",
         ["Usability", "Reliability", "SEO ranking", "Page load speed"],
         1, "MTBF is a classic reliability metric — the average time a system runs before a failure occurs."),
        ("Which best improves perceived usability for a first-time user?",
         ["Hiding all navigation elements", "Clear, consistent UI patterns with helpful onboarding/feedback", "Requiring a manual to use the interface", "Removing all labels from buttons"],
         1, "Consistency and clear feedback reduce the learning curve for someone using the system for the first time."),
        ("A system with high 'availability' (an aspect of reliability) means:",
         ["It has many features", "It is accessible/operational for a high percentage of the intended time", "It has a large user base", "It uses the newest technology"],
         1, "Availability specifically refers to uptime — the proportion of time the system is actually usable."),
    ],

    "nfr-mastery": [
        ("Which of these is a non-functional requirement, rather than a functional one?",
         ["\"The system must let users reset their password\"", "\"The system must support 10,000 concurrent users with under 2s response time\"", "\"The system must display a list of products\"", "\"The system must send a confirmation email after signup\""],
         1, "Functional requirements describe what the system does; non-functional requirements describe quality attributes like performance under load."),
        ("'Scalability' as an NFR refers to a system's ability to:",
         ["Look good on all screen sizes", "Handle increasing load (users, data, transactions) by adding resources without major redesign", "Recover instantly from any failure", "Pass all functional test cases"],
         1, "Scalability is about growing gracefully to handle more load, not about visual design or fault recovery."),
        ("Horizontal scaling means:",
         ["Increasing the power (CPU/RAM) of a single existing server", "Adding more servers/instances to distribute load", "Reducing the number of servers", "Rewriting the application in a faster language"],
         1, "Horizontal scaling adds more machines; vertical scaling makes a single machine more powerful."),
        ("\"The system must encrypt data at rest and in transit\" falls under which NFR category?",
         ["Usability", "Security", "Portability", "Maintainability"],
         1, "Encryption requirements are a core part of a system's security posture."),
        ("'Maintainability' as an NFR is primarily concerned with:",
         ["How easily the system can be modified, fixed, or extended over time", "How fast the UI renders", "How many users can log in simultaneously", "The visual design of the interface"],
         0, "Maintainability is about the long-term cost and ease of changing the system as needs evolve."),
        ("Why are NFRs often harder to verify than functional requirements?",
         ["They don't matter for real systems", "They often require specialized testing (load, security, long-running reliability tests) rather than a simple pass/fail check", "NFRs are always tested manually only", "NFRs can only be verified after deployment"],
         1, "Verifying qualities like performance or reliability typically needs sustained, specialized testing rather than a single functional check."),
    ],

    "web-accessibility": [
        ("What does WCAG stand for?",
         ["Web Content Accessibility Guidelines", "World Compliance and Accessibility Group", "Website Coding and Auditing Guide", "Web Component Access Grid"],
         0, "WCAG (Web Content Accessibility Guidelines) is the widely-adopted standard published by the W3C."),
        ("What is the purpose of an ARIA label?",
         ["To style an element visually", "To provide accessible names/descriptions for assistive technologies, especially for elements without visible text", "To improve page load speed", "To validate form input"],
         1, "ARIA attributes help screen readers and other assistive tech understand elements that lack clear visible text."),
        ("Which WCAG principle (from the POUR framework) relates to content being presentable in different ways without losing information?",
         ["Perceivable", "Operable", "Understandable", "Robust"],
         0, "'Perceivable' covers making content available to the senses — including adaptable presentation for assistive technology."),
        ("Why is sufficient color contrast important for accessibility?",
         ["It's purely a visual design preference with no accessibility impact", "It ensures text is readable for users with low vision or color vision deficiencies", "It only affects print stylesheets", "It has no relation to WCAG"],
         1, "WCAG sets minimum contrast ratios specifically because low contrast makes text hard or impossible to read for many users."),
        ("What's a common accessibility issue with images that lack alt text?",
         ["They load slower", "Screen reader users get no information about the image's content or purpose", "They fail HTML validation only", "They can't be compressed"],
         1, "Alt text is the primary way screen readers convey what an image shows or means."),
        ("Keyboard accessibility (operating a site using only a keyboard) primarily benefits:",
         ["Only users who choose not to use a mouse", "Users with motor impairments, some screen reader users, and power users — a broad range of people", "No real users — it's a theoretical requirement", "Only search engine crawlers"],
         1, "Full keyboard operability is essential for a wide range of real users, not a niche edge case."),
    ],

    "technical-seo-audits": [
        ("What is 'crawl budget'?",
         ["The amount of money spent on SEO tools", "The number of pages a search engine bot will crawl on a site within a given timeframe", "The number of backlinks a site has", "The word count limit per page"],
         1, "Crawl budget describes how much crawling attention a search engine allocates to a given site."),
        ("A canonical tag pointing to a different domain entirely is:",
         ["Always invalid and ignored", "Possible (a cross-domain canonical), used when the same content is legitimately hosted or syndicated elsewhere", "The only way to redirect a page", "Required on every single page"],
         1, "Cross-domain canonicals are a recognized, legitimate technique for syndicated or mirrored content."),
        ("What does structured data (e.g. Schema.org markup) primarily help with?",
         ["Increasing page load speed", "Helping search engines understand page content and enabling rich results (star ratings, FAQs, etc.)", "Encrypting page content", "Reducing server costs"],
         1, "Structured data gives search engines explicit, machine-readable context that can unlock enhanced search listings."),
        ("Why is a 'soft 404' problematic?",
         ["It correctly tells search engines the page doesn't exist", "It returns a 200 (OK) status while showing 'not found' content, confusing search engines about the page's validity", "It's the fastest way to redirect users", "It automatically improves rankings"],
         1, "A soft 404 sends mixed signals — the HTTP status says the page is fine, but the content says otherwise."),
        ("Indexability is primarily affected by:",
         ["Only the page's word count", "Factors like robots.txt rules, noindex tags, canonical tags, and duplicate content signals", "The user's browser", "The page's font choice"],
         1, "Whether a page can be indexed depends on explicit crawl/index directives and duplicate-content handling, not styling."),
        ("Why might a technical SEO audit flag 'orphan pages' (no internal links pointing to them)?",
         ["Orphan pages load faster", "They can be hard for search engines (and users) to discover through normal crawling/navigation", "They automatically get deindexed", "They are always duplicate content"],
         1, "Without internal links, a page relies entirely on external discovery — a real risk to its visibility."),
    ],

    "load-stress-testing": [
        ("What is the main goal of load testing?",
         ["To find every functional bug in an application", "To evaluate system behavior and performance under expected/anticipated levels of concurrent usage", "To test the UI's visual design", "To test a single user's happy-path flow only"],
         1, "Load testing checks how the system performs under realistic, expected traffic levels."),
        ("What distinguishes stress testing from load testing?",
         ["They are identical", "Stress testing pushes the system beyond normal limits to find its breaking point, while load testing evaluates behavior at expected load", "Stress testing only tests databases", "Load testing only runs in production"],
         1, "Stress testing deliberately goes past expected capacity to see how and where the system fails."),
        ("What is a 'breakpoint' in stress testing?",
         ["A debugging tool in an IDE", "The point at which the system fails or performance degrades unacceptably under increasing load", "A scheduled maintenance window", "A type of load balancer"],
         1, "The breakpoint is where the system's performance or availability collapses under load."),
        ("Why simulate 'traffic spikes' during performance testing?",
         ["To validate the system's resilience during sudden, short bursts of unusually high demand (e.g. flash sales, viral traffic)", "To reduce server costs", "To test only average daily usage", "Spikes are irrelevant to real-world systems"],
         0, "Spike testing checks whether the system can absorb sudden surges without failing, which sustained-load testing alone wouldn't reveal."),
        ("What is 'soak testing' (endurance testing) primarily designed to detect?",
         ["UI color inconsistencies", "Issues that only emerge over a sustained period under continuous load, like memory leaks", "Typos in error messages", "Browser compatibility issues"],
         1, "Soak testing runs the system under load for an extended period to surface slow-building issues like resource leaks."),
        ("A key metric commonly monitored during load testing is:",
         ["Number of git commits", "Response time / latency under increasing concurrent load", "Number of open browser tabs", "Code comment density"],
         1, "Latency/response time under load is one of the primary signals of how well a system is coping with traffic."),
    ],

    "quick-meta-tags": [
        ("What's the general guidance for title tag length to avoid truncation in search results?",
         ["There's no practical limit", "Roughly 50–60 characters, since longer titles are often truncated in results", "Exactly 10 characters", "Titles should always exceed 200 characters"],
         1, "Search engines typically display only the first ~50-60 characters of a title before truncating it."),
        ("Which tag sets a page's title, shown in the browser tab and often in search results?",
         ["`<meta name=\"description\">`", "`<title>`", "`<h1>`", "`<link rel=\"canonical\">`"],
         1, "The `<title>` tag is what browsers and search results display as the page's title."),
        ("What happens if a page has no meta description?",
         ["The page cannot be indexed", "Search engines will typically auto-generate a snippet from the page content instead", "The site is penalized permanently", "The page automatically gets noindexed"],
         1, "A missing meta description just means the search engine picks its own snippet — it's not a penalty."),
        ("A canonical tag with `href` pointing to the page itself (self-referencing) is:",
         ["An error that should always be avoided", "A common, often-recommended practice to reduce ambiguity about the preferred URL", "Only valid on the homepage", "The same as a noindex tag"],
         1, "Self-referencing canonicals are a standard, widely-recommended practice, not a mistake."),
        ("Which of these is a meta tag best practice?",
         ["Writing a unique, descriptive meta description for each important page", "Copying the exact same meta description across every page", "Leaving meta descriptions blank on purpose", "Filling meta descriptions with unrelated keywords"],
         0, "Unique, relevant descriptions per page give users (and search snippets) an accurate, distinct preview."),
        ("The meta description tag primarily influences:",
         ["Direct ranking position via a ranking algorithm signal", "Click-through rate from search results, by giving users a preview of the page", "The page's load speed", "The page's canonical URL"],
         1, "It's not a direct ranking factor, but a well-written one can meaningfully improve click-through rate."),
    ],

    "smoke-testing-basics": [
        ("When is a smoke test typically run?",
         ["Only once a year", "After a new build/deployment, before deeper testing, to confirm critical functionality works", "Only by end users in production", "Never — it's an outdated practice"],
         1, "Smoke tests are a fast first gate right after a new build, before investing in deeper testing."),
        ("What does a smoke test typically check?",
         ["Every possible edge case in the application", "The most critical, high-level functions to confirm the build is stable enough for further testing", "Only the database schema", "Only the visual design"],
         1, "It's intentionally shallow and broad — critical paths only, not exhaustive coverage."),
        ("If a smoke test fails, what usually happens next?",
         ["The build is typically rejected/returned, since deeper testing would be a waste of time on an unstable build", "Testing continues as normal, ignoring the failure", "Only the UI team is notified", "The application is automatically deployed anyway"],
         0, "A failed smoke test signals the build isn't stable enough to justify further testing effort yet."),
        ("The term 'smoke test' originates from a similar concept in which field?",
         ["Software only, with no outside origin", "Hardware/electrical engineering — checking if a device smokes when first powered on", "Cooking", "Aviation navigation"],
         1, "The term comes from hardware testing, where powering on a device and checking for smoke was a first basic check."),
        ("Smoke testing is best described by which test scope?",
         ["Exhaustive and deep", "Shallow and wide — a broad but quick pass over critical functionality", "Narrow and deep on a single module", "Purely load-based"],
         1, "It trades depth for speed and breadth, covering critical areas quickly rather than thoroughly."),
        ("Which is a good candidate to include in a smoke test suite for a web app?",
         ["Every possible input combination for every form", "Core flows like 'can a user log in' and 'does the homepage load'", "Rare edge-case error messages only", "Detailed performance benchmarking"],
         1, "Smoke tests focus on the handful of flows that, if broken, mean nothing else is worth testing yet."),
    ],

    "mobile-viewport-essentials": [
        ("What does the viewport meta tag primarily control?",
         ["The page's color scheme", "How a webpage is scaled and displayed on a mobile device's screen", "The server's response time", "The page's title"],
         1, "It tells the mobile browser how to size and scale the page's layout viewport."),
        ("Without a viewport meta tag, mobile browsers often:",
         ["Automatically apply mobile-first styles", "Render the page at a fixed desktop-like width (e.g. 980px) and scale it down, making text tiny", "Refuse to load the page", "Block all images"],
         1, "Mobile browsers fall back to a wide default viewport, which shrinks everything and hurts readability."),
        ("What does `initial-scale=1` in a viewport meta tag do?",
         ["Sets the initial zoom level to match the device width 1:1", "Doubles the page size", "Disables all zooming", "Sets the page to landscape mode"],
         0, "`initial-scale=1` establishes a 1:1 pixel ratio between CSS pixels and the device's viewport on load."),
        ("A 'mobile-friendly' test typically checks for issues like:",
         ["Server database indexing", "Text too small to read, clickable elements too close together, content wider than the screen", "The number of git branches", "CSS file naming conventions"],
         1, "Mobile-friendliness checks focus on real usability problems specific to small touchscreens."),
        ("Which CSS approach helps avoid horizontal scrolling on mobile?",
         ["Using fixed pixel widths larger than the viewport", "Using relative/fluid units (%, vw) and `max-width: 100%` on elements", "Disabling the viewport meta tag", "Increasing font size to 100px"],
         1, "Fluid sizing keeps elements within the available viewport width instead of overflowing it."),
        ("Why is tap target size (button/link size) important on mobile?",
         ["It affects server load", "Small tap targets are hard to accurately tap with a finger, hurting usability", "It changes the page's meta description", "It has no real usability impact"],
         1, "Finger-based interaction needs larger touch targets than a precise mouse pointer does."),
    ],

    "canonical-redirects-quickfire": [
        ("A 301 redirect indicates:",
         ["A temporary redirect", "A permanent redirect, passing most ranking signals to the new URL", "A server error", "A client-side JavaScript redirect only"],
         1, "301 explicitly signals a permanent move, and search engines generally consolidate ranking signals to the new URL."),
        ("A 302 redirect indicates:",
         ["A permanent redirect", "A temporary redirect, generally not intended to pass long-term ranking signals the way a 301 does", "A 'page not found' error", "A canonical tag alternative with identical handling to a 301"],
         1, "302 signals the move is temporary, so search engines historically treat it differently from a 301 for ranking purposes."),
        ("What is a 'redirect chain'?",
         ["A single, direct redirect from A to B", "A sequence of multiple redirects (A → B → C) before reaching the final destination", "A type of canonical tag", "A CDN caching strategy"],
         1, "Each extra hop in a chain adds latency and can dilute ranking signal transfer."),
        ("When should you use a canonical tag instead of a redirect?",
         ["When you want users automatically sent to a different URL", "When multiple similar/duplicate URLs should stay accessible, but you want to indicate one preferred version to search engines", "Canonical tags and redirects always have identical effects", "Never — canonical tags are deprecated"],
         1, "A canonical tag is for signaling preference among URLs that all still need to remain reachable; a redirect actually moves users."),
        ("What's a common negative effect of a long redirect chain?",
         ["Improved page speed", "Added latency and potential loss of some link equity/ranking signal at each hop", "Automatic ranking boost", "No effect at all"],
         1, "Every hop costs a round trip and can weaken the signal passed to the final destination."),
        ("If a page has permanently moved to a new URL, which is generally recommended?",
         ["A 302 temporary redirect", "A 301 permanent redirect to the new URL", "A canonical tag pointing back to the old URL", "No action needed"],
         1, "A permanent move should be communicated with a 301, which is built for exactly this case."),
    ],

}
