# Generated by Django 6.0.7 on 2026-07-23 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall', models.PositiveSmallIntegerField(default=0)),
                ('ml_score', models.FloatField(default=0)),
                ('grade', models.CharField(blank=True, max_length=40)),
                ('categories', models.JSONField(blank=True, default=dict)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('errors_count', models.PositiveSmallIntegerField(default=0)),
                ('warnings_count', models.PositiveSmallIntegerField(default=0)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('max_xp', models.PositiveIntegerField(default=0)),
                ('completed_indexes', models.JSONField(blank=True, default=list)),
                ('earned_badges', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
