# Generated by Django 6.0.7 on 2026-07-30 07:55

import frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_learnerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerprofile',
            name='difficulty_level',
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='difficulty_levels',
            field=models.JSONField(default=frontend.models._default_difficulty_levels),
        ),
    ]
