# Generated by Django 6.0.7 on 2026-07-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_learnerprofile_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='interests',
            field=models.JSONField(default=list),
        ),
    ]
